<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AlgoTrader.Backtesting</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoTrader.Domain\AlgoTrader.Domain.csproj" />
    <ProjectReference Include="..\AlgoTrader.Application\AlgoTrader.Application.csproj" />
    <ProjectReference Include="..\AlgoTrader.Strategy\AlgoTrader.Strategy.csproj" />
    <ProjectReference Include="..\AlgoTrader.Risk\AlgoTrader.Risk.csproj" />
  </ItemGroup>

</Project>
